---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelservice
spec:
  selector:
    matchLabels:
      app: hotelservice
  template:
    metadata:
      labels:
        app: hotelservice
    spec:
      containers:
      - name: hotelservice
        image: abdulsammadkhan49453/hotelapp
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: test1234
              # secretKeyRef:
              #   name: mysql-secret
              #   key: password
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hotelservice
spec:
  type: NodePort
  selector:
    app: hotelservice
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30000
